CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  input_size: 6
  output_size: 4
  embed_size: 64
DATA:
  root: "../data"
  batch_size: 8
  N: 100 # num points in image plane
  M: 32 # num query points per ray
  tn: 2 # near distance ray
  tf: 6 # far distance ray
  img_plane_h: 100
  img_plane_w: 100
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.00005
  weight_decay_step: 100
  num_epochs: 100
