CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  input_size: 5
  output_size: 3
  embed_size: 256
DATA:
  root: "../data"
  batch_size: 128
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.00005
  weight_decay_step: 100
  num_epochs: 100