CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  input_size: 6
  output_size: 4
  embed_size: 256
DATA:
  root: "../data"
  batch_size: 2
  N: 10   
  M: 20
  tn: 1
  tf: 3
  img_plane_h: 64
  img_plane_w: 64
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.00005
  weight_decay_step: 100
  num_epochs: 100