CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  input_size: 6
  output_size: 4
  embed_size: 64
DATA:
  root: "../data"
  batch_size: 1
  N: 2048 # num points in image plane
  M: 32 # num query points per ray
  tn: 2 # near distance ray
  tf: 6 # far distance ray
  H: 100
  W: 100
OPTIM:
  optimizer: "AdamW"
  lr: 0.0005
  num_epochs: 100000
  eval_every: 5
