CKPT_DIR: "../artifacts/ckpts"
LOG_DIR: "../artifacts/logs"
IMG_OUT_DIR: "../artifacts/img"
MODEL:
  input_size: 6
  output_size: 4
  embed_size: 256
DATA:
  root: "../data"
  batch_size: 2
  N: 10 # num points in image plane
  M: 20 # num query points per ray
  tn: 1 # near distance ray
  tf: 3 # far distance ray
  img_plane_h: 50
  img_plane_w: 50
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  weight_decay: 0.00005
  weight_decay_step: 100
  num_epochs: 100
